### ISSUE TITLE
Two Issues with the Dockerfile

### ISSUE THREAD

**Issue by jfilter** [skorokithakis/django-project-template#4]
Hey,

thanks for the amazing template. I am a Django rookie and it really helped me to get started but I had to add two lines to the Dockerfile (besides downgrading Pipenv because there is a bug in the current version):

1. Pipenv didn't find Python so I just linked it
`RUN ln -sf /usr/local/bin/python /bin/python`

2. ./code/manage.py was not executable
`RUN chmod +x /code/manage.py`

Did I do something wrong?

**Comment by skorokithakis** [comment]
Thanks, i'm glad you liked it! Hmm, I can't really reproduce your issues... Python works fine for me, and `manage.py` is executable in the repo. Are you on Windows, maybe? Or maybe you downloaded the zip file instead of cloned the repo?

**Comment by jfilter** [comment]
No, I am on macOS and I ran the `django-admin` command. But let's close this. If somebody has trouble, they can find help here. ;)

**Comment by jfilter** [comment]
I guess I know now why this happens. The `django-admin` command downloads the zip file and therefore the file properties are lost:

```
django-admin.py startproject \
  --template=https://github.com/skorokithakis/django-project-template/archive/master.zip \
  --extension py,cfg,yml,ini \
  project_name
```

**Comment by skorokithakis** [comment]
Hmm, that's odd. It works for me and the properties are preserved. Maybe the unzip command does something funky on OS X?
