### ISSUE TITLE
docker compose file update

### ISSUE THREAD

**Issue by morenoh149** [skorokithakis/django-project-template#7]
The compose file in this project would not work for me. After much debugging and following https://docs.docker.com/compose/django/ I got something working.

Would a PR for a compose file using version 3 syntax be welcome?

**Comment by skorokithakis** [comment]
Yes, definitely. Does version 2 not work any more?

**Comment by morenoh149** [comment]
submitted a PR. There are no actual changes required to make the existing compose file be version 3 compliant. I just found it annoying as a beginner, as I'm not sure if the version would matter. Made the compose file closer to what the docker quickstart shows.
